### ISSUE TITLE
y2logsstep -> get_ip_address does not work during TW installation

### ISSUE THREAD

**Issue by Vogtinator** [os-autoinst/os-autoinst-distri-opensuse#1024]
get_ip_address always uses "ifconfig -a", although that is not available during the installation.
See also https://openqa.opensuse.org/tests/118360/modules/livecdreboot/steps/2 "ifconfig: command not found".
Can this be migrated to "ip addr show"?

**Comment by coolo** [comment]
please use progress.opensuse.org to track issues. otherwise we have just too many places to check
