### ISSUE TITLE
openQA test case sle-11-SP4-Alpha-Server-DVD-ppc64-Build0917-ha got interrupted

### ISSUE THREAD

**Issue by Zaoliang** [os-autoinst/os-autoinst-distri-opensuse#297]
please see test case at: https://openqa.suse.de/tests/15111

logs can be found at: https://openqa.suse.de/tests/15111/file/autoinst-log.txt

**Comment by coolo** [comment]
I'm not sure what sense it makes to report such issues here

**Comment by Zaoliang** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 04.03.2015 16:24, Stephan Kulow wrote:
> I'm not sure what sense it makes to report such issues here
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/os-autoinst/os-autoinst-distri-opensuse/issues/297#issuecomment-77177505
>
> 
Since we use openQA for validation test and for any kind of issues
related to tests we need to be reported.

Please tell me where I should report this kind of issue of openQA than
github, thanks.



- -- 
Zaoliang Luo
Quality Assurance Department
Phone +49 91174053-363
SUSE Linux GmbH
GF: Felix Imendörffer, Jane Smithard, Jennifer Guild, Dilip
Upmanyu, Graham Norton, HRB 21284 (AG Nürnberg)
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBAgAGBQJU9ypqAAoJEJz+DN4alluEjnQH/An5Lt/0Si7TbcEAbmZC2u0L
s0Xzg5IHEsGUmETlYeYQiqsnlIMN07OHDPxxNaSbOz0VUU2i1swWgZl2EBV8MIBY
LxWY4LMLbIK8n02/Q5b7xjfUV1bwVyqQGmNv/4IPcNH5XbjkEbHz48c3GhUxjtHT
7k1ANChH5p0zVtYrWEyoK6oMu5q1oXURinvIg73PC1DSI8djXLvH5yEbGveDNNLO
EpXO1A7O+Z8mInCtRgW+06zBvejVXMT47r28I2sz5Wye6pWNUxD538fe6jQU+Rfo
oICtdUwqgN/XArvGYtyMYXUP6UIttSFThgFanXbosMT7AKuIZE7fJt9DrbpLxQ0=
=RWiZ
-----END PGP SIGNATURE-----

**Comment by sysrich** [comment]
I think this is the best place (for now at least) to report issues with the tests

This particular issue looks like PPC cannot handle VM snapshotting properly. I know Dinar is aware of it already, but lets leave the issue open to remind me to track it with him, as this will require infra changes to the workers in order to be able to handle snapshots properly

**Comment by nilxam** [comment]
I believe Dinar tried to fix it on https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/299 , so looks for some reason. the audio test will not work on ppc system.

**Comment by nilxam** [comment]
wow, @sysrich we leave the comment at the same time :)
