### ISSUE TITLE
upload dracut logs in case initrd fails

### ISSUE THREAD

**Issue by k0da** [os-autoinst/os-autoinst-distri-opensuse#475]
Would be cool to have logs grabbed in case dracut fails.

Like here: https://openqa.opensuse.org/tests/65694/modules/first_boot/steps/6

**Comment by k0da** [comment]
I propose to create a needle with dracut login with linux-login tag. Then grab rdsoreport.

**Comment by coolo** [comment]
file it on progress.opensuse.org - our test tasks have a project there
